/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // htmlSidebar: [{ type: "autogenerated", dirName: "html" }],
  cssSidebar: [{ type: "autogenerated", dirName: "css" }],
  othersSidebar: [{ type: "autogenerated", dirName: "others" }],
  plusSidebar: [{ type: "autogenerated", dirName: "plus" }],
}; // Cleaning content

module.exports = sidebars;
